# Generated by Django 5.0.6 on 2024-09-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='start',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Start', 'verbose_name_plural': 'Starts'},
        ),
    ]
